FROM ghcr.io/amiorin/big-container:latest

ENV DOTFILES="/home/${DEVBOX_USER}/code/personal/dotfiles-v3/main"
COPY --chown=${DEVBOX_USER} dotfiles-v3/main ${DOTFILES}
RUN cd ${DOTFILES} \
    && xterm-ghostty | tic -x - \
    && bb install -p ubuntu

# ENV DOTFILES="/home/${DEVBOX_USER}/code/personal/dotfiles-v3/main"
# RUN git clone https://github.com/amiorin/dotfiles-v3.git ${DOTFILES} \
#     && cd ${DOTFILES} \
#     && cat xterm-ghostty | tic -x - \
#     && bb install -p ubuntu
