name: Build and Push Docker Image to GHCR
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*.md"
      - "/.github/**"
      - "/.gitignore"
    branches:
      - main
jobs:
  build-and-push-:
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
